title: Chris Bobbe
subtitle: Web Developer
description: Website and portfolio of Chris Bobbe, front-end web developer.
# You'll want to customize baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

author: Chris Bobbe
email: csbobbe@gmail.com
country: United States of America

# Social settings
facebook_url: https://www.facebook.com/chris.bobbe
github_url: https://github.com/chrisbobbe
linkedin_url: https://www.linkedin.com/in/chrisbobbe1995/
twitter_url: https://twitter.com/chrisbobbe

# SEO settiongs
google_analytics: UA-112211352-1

# Build settings
markdown: kramdown
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-feed
      
# Necessary for Prologue theme:
collections: [sections]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
