title: Loïc Herbelot
subtitle: Data Scientist
description: My website and portfolio.

author: Loïc Herbelot
email: csbobbe@gmail.com
avatar: assets/images/avatar.jpg

baseurl: ""
url: "https://loich.github.io"

# Social settings
github_url: https://github.com/LoiH
linkedin_url: https://www.linkedin.com/in/herbelot/


# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]

theme: jekyll-theme-prologue
